config/routes.rb
Rails.application.routes.draw do

  #googleAPI
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'home#top'
  get 'about', to: 'home#about'
  get "search", to: "users#search"

  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 500}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/level_setting.rb
class LevelSetting < ApplicationRecord
  validates :level, uniqueness: true
  validates :threshold, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_relations

  attachment :post_image

  validates :post, presence: true, length: { maximum: 500}

  # 引数で渡されたユーザidがFavoritesテーブル内user_idカラムに存在（exists?）するかどうかを調べる
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image, destroy: false

  # バリデーション
  validates :name, presence: true, length: { maximum: 20 }
  validates :profile, length: { maximum: 100 }
  validates :email, presence: true
# ゲストログイン
  def self.guest
    User.find_by(email: 'guest1@guest1')
  end
# google API
  protected
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    unless user
      user = User.create!(
        name: auth.info.name,
        email: auth.info.email,
        provider: auth.provider,
        uid: auth.uid,
        token: auth.credentials.token,
        password: Devise.friendly_token[0, 20],
        meta: auth.to_yaml)
    end
    user
  end
#検索機能
  def self.search(search)
    User.where(['name LIKE ?', "%#{search}%"])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @user = current_user
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = post.id
    @comment.save
      if @comment.save
        @user.experience +=1
        @user.save
        levelSetting = LevelSetting.find_by(level: @user.user_level + 1)
        if levelSetting.threshold <= @user.experience
          @user.user_level = @user.user_level + 1
          @user.update(user_level: @user.user_level)
        end
        redirect_to post_path(post)
      else
        redirect_to post_path(post)
      end
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end
  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.find_for_google(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      flash[:notice] = "ログインしました"
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # def new
  #   @post = Post.new(post_params)
  #   @post.user_id = current_user.id
  #   if @post.save
  #     @posts = Post.all
  #     @user.experience +=1
  #     @user.save
  #     levelSetting = LevelSetting.find_by(level: @user.user_level + 1)
  #     if levelSetting.threshold <= @user.experience
  #         @user.user_level = @user.user_level + 1
  #         @user.update(user_level: @user.user_level)
  #     end
  #   else
  #     render 'index'
  #   end
  # end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @user = current_user
    @posts = Post.page(params[:page]).per(5).order("created_at DESC")
    if @post.save
      @user.experience +=1
      @user.save
      levelSetting = LevelSetting.find_by(level: @user.user_level + 1)
      if levelSetting.threshold <= @user.experience
          @user.user_level = @user.user_level + 1
          @user.update(user_level: @user.user_level)
      end
      redirect_to posts_path
    else
      render 'index'
    end
  end

  def index
    @posts = Post.page(params[:page]).per(5).order("created_at DESC")
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def edit
  end

  def update
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:post, :post_image, :user_id)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = @user.posts.page(params[:page]).per(5).order("created_at DESC")
    @posts = Post.all
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
			redirect_to user_path(current_user.id)
		end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success_notice] = '変更しました'
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def search
    @users = User.search(params[:search])
    render "index"
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile, :profile_image, :user_level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if post.favorited_by?(current_user) %>
  <div class="flex-fill d-flex justify-content-center">
    <%= link_to post_favorites_path(post), method: :delete, remote: true do %>
      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
      <%= post.favorites.count %>
    <% end %>
  </div>
<% else %>
  <div class="flex-fill d-flex justify-content-center">
    <%= link_to post_favorites_path(post), method: :post, remote: true do %>
      <i class="far fa-heart" aria-hidden="true"></i>
      <%= post.favorites.count %>
    <% end %>
  </div>
<% end %>

app/views/favorites/create.js.erb
 <%# #favorites_buttons_<%= @post.id %>
 <%# ↑部分のHTMLだけ、renderで部分的に更新するという処理 %>
$('#favorites_buttons_<%= @post.id %>').html("<%= escape_javascript(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= escape_javascript(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/posts/_posts.html.erb
  <% posts.each do |post| %>
      <div class="post-content">
        <%= link_to post_path(post.id), data: {"turbolinks"=>false} do %>
          <div class="row">
              <div class="col-2">
                <%= attachment_image_tag post.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", class: "profile-image-mini" %>
              </div>
              <div class="col-7 post-name">
                <%= post.user.name %> Lv.<%= post.user.user_level %>
              </div>
              <div class="col-3 post-date">
                <%= post.created_at.strftime('%Y/%m/%d') %>
              </div>
          </div>
          <div class="row">
            <div class="col-2"></div>
            <div class="col-10">
              <div class="row post-text">
                <small><%= simple_format post.post %></small>
              </div>
              <div class="row post-image">
                  <%= attachment_image_tag post, :post_image, format: 'jpeg', size: "420x280", class: "post-image" %>
              </div>
            </div>
          </div>
        <% end %>
        <%# --------------------------- %>
        <%# 投稿下部--------------------- %>
        <div class="row">
          <div class="col-2"></div>
          <div class="col">
            <ul class="list-group list-group-horizontal">
              <%# いいね %>
              <li class="list-group-item  flex-fill d-flex justify-content-center" id="favorites_buttons_<%= post.id %>">
                <%= render partial: 'favorites/favorite', locals: { post: post} %>
              </li>
              <%# ------- %>
              <%# コメント %>
              <li class="list-group-item flex-fill d-flex justify-content-center">
                <%= link_to post_path(post.id), data: {"turbolinks"=>false} do %>
                  <i class="far fa-comment-dots btn-outline-info"></i>
                  <%= post.comments.count %>
                <% end %>
              </li>
              <%# -------- %>
              <%# 削除 %>
              <% if post.user == current_user %>
                <li class="list-group-item flex-fill d-flex justify-content-center">
                  <%= link_to post_path(post), method: :delete, class: 'btn-sm btn-outline-danger' do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </li>
              <% end %>
              <%# ---- %>
            </ul>
          </div>
        </div>
        <%# ---------------------------- %>
      </div>
    <% end %>

app/views/posts/create.js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.posts').html("<%= escape_javascript(render 'posts', posts: @posts) %>")

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
  <h4><i class="fas fa-home mb-10"> ホーム</i></h4>
  <%# 投稿フォーム %>
  <div class="row post-form">
    <%= attachment_image_tag current_user, :profile_image, fallback: "no_image.jpg", size:"50x50", class: "profile-image" %>
    <div class="col">
      <%= form_with(model: @post, local: true) do |f| %>
          <%= f.text_area :post, rows: "3", id: "post-form", class: "col form-control", placeholder: "お金・友達・筋肉について語ろう" %>
          <%= f.attachment_field :post_image, placeholder: "画像" %>
          <%= f.submit "投稿", class: "btn btn-outline-success col-xs-12 mt-2" %>
      <% end %>
    </div>
  </div>
  <%# ---------- %>
  <%# 固定ボタン------ %>
  <button type="button" class="btn btn-success fixed_btn" data-toggle="modal" data-target="#exampleModal">
    <i class="far fa-paper-plane"></i>
  </button>
  <%# ---------------- %>

  <%# modal-form %>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">新規投稿</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= form_with(model: @post) do |f| %>
          <div class="modal-body">
            <div class="form-group">
              <%= f.text_area :post, rows: "8", class: "form-control", placeholder: "お金・友達・筋肉について語ろう" %>
            </div>
            <div class="form-group">
              <%= f.attachment_field :post_image, placeholder: "画像" %>
            </div>
          </div>
          <div class="modal-footer">
            <button button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
            <%= f.submit "投稿する", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%# ---------- %>
  <!--posts一覧 -->
  <div class="jscroll">
  <%# 非同期投稿 %>
  <div class="posts">
    <%= render 'posts', posts: @posts %>
  </div>
  <%# ----------- %>

    <%= paginate @posts %>
  </div>
  <%# --------------------------- %>
</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
  <%# 投稿フォーム %>
  <div class="row justify-content-md-center">
    <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size:"100x100", class: "profile-image" %>
  </div>
  <div class="row justify-content-md-center">
   <div class="form-body">
      <%= form_with(model: @post, local: true) do |f| %>
          <%= f.text_area :post, rows: "8", class: "col form-control", placeholder: "なんか書いとけ" %>
          <%= f.attachment_field :post_image, placeholder: "画像" %>
          <%= f.submit "投稿", class: "btn btn-primary pull-right" %>
      <% end %>
    </div>
  </div>
  <%# ---------------- %>

app/views/posts/new.js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.posts').html("<%= escape_javascript(render 'posts', posts: @posts) %>")

app/views/posts/show.html.erb
<div class="container mb-5">
  <%# 投稿全体 %>
  <div class="post-content mb-4">
    <%# 投稿上部 %>
    <div class="row">
        <div class="col-2">
          <%= link_to user_path(@post.user_id) do %>
            <%= attachment_image_tag @post.user, :profile_image, fallback: "no_image.jpg", size: "50x50", class: "profile-image-mini" %>
        </div>
        <div class="col-7 post-name">
            <%= @post.user.name %>
          <% end %>
        </div>
      <div class="col-3 post-date">
        <%= @post.created_at.strftime('%Y/%m/%d') %>
      </div>
    </div>
    <%# -------- %>
    <%# 投稿中部 %>
      <div class="row">
        <div class="col-2"></div>
        <div class="col-10">
          <div class="row post-text">
            <small><%= simple_format @post.post %></small>
          </div>
          <div class="row post-image">
            <%= attachment_image_tag @post, :post_image, format: 'jpeg', size: "420x280", class: "post-image" %>
          </div>
        </div>
      </div>
    <%# ------------ %>
    <%# 投稿下部--------------------- %>
    <div class="row">
      <div class="col-2"></div>
      <div class="col">
        <ul class="list-group list-group-horizontal">
          <%# いいね %>
          <li class="list-group-item flex-fill" id="favorites_buttons_<%= @post.id %>">
            <%= render partial: 'favorites/favorite', locals: { post: @post} %>
          </li>
          <%# ------- %>
          <%# コメント %>
          <li class="list-group-item flex-fill d-flex justify-content-center">
            <%= link_to post_path(@post.id) do %>
              <i class="far fa-comment-dots btn-outline-info"></i>
              <%= @post.comments.count %>
            <% end %>
          </li>
          <%# -------- %>
          <%# 削除 %>
          <% if @post.user == current_user %>
            <li class="list-group-item flex-fill d-flex justify-content-center">
              <%= link_to post_path(@post), method: :delete, class: 'btn-sm btn-outline-danger' do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </li>
          <% end %>
          <%# ---- %>
        </ul>
      </div>
    </div>
      <%# ---------------------------- %>
  </div>
  <%# コメント入力機能----------------- %>
  <h5>コメント入力</h5>
  <div class="row mb-2">
    <div class="col">
      <%= form_with model:[@post, @comment], local: true do |f| %>
        <%= f.text_area :comment, class: ("form-control :width'100%"), placeholder: "コメントをここに" %>
    </div>
        <%= f.submit "送信する", class: "btn btn-success pull-right" %>
      <% end %>
  </div>
  <%# ---------------------------------- %>

  <ul class="list-group list-group-flush">
    <% @post.comments.each do |comment|%>
      <li class="list-group-item comment">
        <%# コメントしたユーザー情報 %>
        <div class="row">
            <div class="col-2">
              <%= link_to user_path(comment.user) do %>
                <%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", class: "comment-user-img" %>
              <% end %>
            </div>
            <div class="col-7">
              <div class="comment-name">
                <%= comment.user.name %>
              </div>
            </div>
            <div class="col-3">
              <div class="post-date">
                <%= comment.created_at.strftime('%Y/%m/%d') %>
              </div>
            </div>
          <div class="col-2"></div>
          <div class="col-10">
            <div class="comment-text">
              <%# コメント本文 %>
              <small><%= comment.comment %></small>
              <%# ------------ %>
            </div>
              <%# コメント本人であれば削除を表示 %>
              <div class="d-flex flex-row-reverse">
                <% if comment.user == current_user %>
                  <%= link_to post_comment_path(comment.post, comment), class: 'btn-sm btn-outline-danger', method: :delete do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </div>
              <%# ------------------------------ %>
          </div>
        </div>
      </li>
    <% end%>
  </ul>

</div>