config/routes.rb
Rails.application.routes.draw do

  #googleAPI
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'home#top'
  get 'about', to: 'home#about'
  get "search", to: "users#search"

  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image, destroy: false

  # バリデーション
  validates :name, presence: true, length: { maximum: 20 }
  validates :profile, length: { maximum: 100 }
  validates :email, presence: true
# ゲストログイン
  def self.guest
    User.find_by(email: 'guest1@guest1')
  end
# google API
  protected
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    unless user
      user = User.create!(
        name: auth.info.name,
        email: auth.info.email,
        provider: auth.provider,
        uid: auth.uid,
        token: auth.credentials.token,
        password: Devise.friendly_token[0, 20],
        meta: auth.to_yaml)
    end
    user
  end
#検索機能
  def self.search(search)
    User.where(['name LIKE ?', "%#{search}%"])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def new_guest
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = @user.posts.page(params[:page]).per(5).order("created_at DESC")
    @posts = Post.all
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
			redirect_to user_path(current_user.id)
		end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success_notice] = '変更しました'
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def search
    @users = User.search(params[:search])
    render "index"
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile, :profile_image, :user_level)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/comfirm.html.erb
<h1>Users#comfirm</h1>
<p>Find me in app/views/users/comfirm.html.erb</p>

app/views/users/edit.html.erb
<div class='container'>


	<h2>プロフィール編集</h2>

	<div class="form-body">

		<%= form_with(model: @user, local: true) do |f| %>
			<div class="form-group">
				<span class="fa fa-user form-control-icon" aria-hidden="true"></span>
				<%= f.label :name, "名前" %>
				<%= f.text_field :name, autofocus: true, placeholder:"名前", class: "form-control"%>
			</div>


			<div class="form-group"><!--profile_image-->
				<span class="fas fa-file-image" aria-hidden="true"></span>
				<%= f.label :profile_image, "プロフィール画像" %>
				<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control" %>
			</div>


			<div class="form-group"><!--profile-->
				<span class="fa fa-user form-control-icon" aria-hidden="true"></span>
				<%= f.label :profile, "プロフィール" %>
				<%= f.text_area :profile, rows: "5", class: "form-control" %>
			</div>

			<div class="edit-btn">
				<%= f.submit "編集", class: "btn btn-outline-success" %>
			</div>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h4><i class="fas fa-users mb-10"> メンバーズ</i></h4>
<%# 検索 %>
  <%= form_with(url: search_path, method: :get, local: true) do |f| %>
    <%= f.text_field :search %>
    <%= f.submit 'Search' %>
  <% end %>
<%# ---- %>
  <% @users.each do |user| %>
  <div class="list-group list-group-item profile-list">
    <%= link_to user_path(user.id) do %>
      <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50", class: "profile-image-mini"%>
      <%= user.name %> Lv.<%= user.user_level %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/users/new.js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.posts').html("<%= escape_javascript(render 'posts', posts: @posts) %>")

app/views/users/show.html.erb
<div class="container">
  <h4><i class="fas fa-user"> プロフィール</i></h4>

  <%# ユーザープロフィール %>
  <div class="row profile-outline">
    <div class="col-3">
        <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", class: "profile-image" %>
    </div>
    <div class="col-9">
      <div class="profile-area">
        <span class="profile-name"><%= @user.name %> Lv.<%= @user.user_level %></span>
        <span class="profile-icon">
          <% if @user == current_user %>
            <%= link_to edit_user_path(@user) do %>
              <i class="fas fa-user-cog btn-outline-success"></i>
            <% end %>
          <% end %>
        </span>
        <div class="profile-text"><%= @user.profile %></div>
      </div>
    </div>
  </div>
  <%# --------------------- %>

  <%# 投稿一覧（本人分） %>
   <div class="jscroll">
    <% @post.each do |post| %>
      <div class="post-content">
        <%= link_to post_path(post.id), data: {"turbolinks"=>false} do %>
          <div class="row">
              <div class="col-2">
                <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50", class: "profile-image-mini" %>
              </div>
              <div class="col-7 post-name">
                <%= post.user.name %>
              </div>
              <div class="col-3 post-date">
                <%= post.created_at.strftime('%Y/%m/%d') %>
              </div>
          </div>

          <div class="row">
            <div class="col-2"></div>
            <div class="col-10">
              <div class="row post-text">
                <%= post.post %>
              </div>
              <div class="row post-image">
                  <%= attachment_image_tag post, :post_image, format: 'jpeg', size: "420x280", class: "post-image" %>
              </div>
            </div>
          </div>
        <% end %>
        <%# --------------------------- %>
        <%# 投稿下部--------------------- %>
        <div class="row">
          <div class="col-2"></div>
          <div class="col">
            <ul class="list-group list-group-horizontal">
              <%# いいね %>
              <li class="list-group-item flex-fill" id="favorites_buttons_<%= post.id %>">
                <%= render partial: 'favorites/favorite', locals: { post: post} %>
              </li>
              <%# ------- %>
              <%# コメント %>
              <li class="list-group-item flex-fill d-flex justify-content-center">
                <%= link_to post_path(post.id) do %>
                  <i class="far fa-comment-dots btn-outline-info"></i>
                  <%= post.comments.count %>
                <% end %>
              </li>
              <%# -------- %>
              <%# 削除 %>
              <% if post.user == current_user %>
                <li class="list-group-item flex-fill d-flex justify-content-center">
                  <%= link_to post_path(post), method: :delete, class: 'btn-sm btn-outline-danger' do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </li>
              <% end %>
              <%# ---- %>
            </ul>
          </div>
        </div>
        <%# ---------------------------- %>
      </div>
    <% end %>
    <%= paginate @post %>
  </div>
  <%# --------------------------- %>
</div>