config/routes.rb
Rails.application.routes.draw do

  #googleAPI
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'home#top'
  get 'about', to: 'home#about'
  get "search", to: "users#search"

  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 500}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/level_setting.rb
class LevelSetting < ApplicationRecord
  validates :level, uniqueness: true
  validates :threshold, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_relations

  attachment :post_image

  validates :post, presence: true, length: { maximum: 500}

  # 引数で渡されたユーザidがFavoritesテーブル内user_idカラムに存在（exists?）するかどうかを調べる
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image, destroy: false

  # バリデーション
  validates :name, presence: true, length: { maximum: 20 }
  validates :profile, length: { maximum: 100 }
  validates :email, presence: true
# ゲストログイン
  def self.guest
    User.find_by(email: 'guest1@guest1')
  end
# google API
  protected
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    unless user
      user = User.create!(
        name: auth.info.name,
        email: auth.info.email,
        provider: auth.provider,
        uid: auth.uid,
        token: auth.credentials.token,
        password: Devise.friendly_token[0, 20],
        meta: auth.to_yaml)
    end
    user
  end
#検索機能
  def self.search(search)
    User.where(['name LIKE ?', "%#{search}%"])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @user = current_user
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = post.id
    @comment.save
      if @comment.save
        @user.experience +=1
        @user.save
        levelSetting = LevelSetting.find_by(level: @user.user_level + 1)
        if levelSetting.threshold <= @user.experience
          @user.user_level = @user.user_level + 1
          @user.update(user_level: @user.user_level)
        end
        redirect_to post_path(post)
      else
        redirect_to post_path(post)
      end
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end
  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.find_for_google(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      flash[:notice] = "ログインしました"
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # def new
  #   @post = Post.new(post_params)
  #   @post.user_id = current_user.id
  #   if @post.save
  #     @posts = Post.all
  #     @user.experience +=1
  #     @user.save
  #     levelSetting = LevelSetting.find_by(level: @user.user_level + 1)
  #     if levelSetting.threshold <= @user.experience
  #         @user.user_level = @user.user_level + 1
  #         @user.update(user_level: @user.user_level)
  #     end
  #   else
  #     render 'index'
  #   end
  # end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @user = current_user
    @posts = Post.page(params[:page]).per(5).order("created_at DESC")
    if @post.save
      @user.experience +=1
      @user.save
      levelSetting = LevelSetting.find_by(level: @user.user_level + 1)
      if levelSetting.threshold <= @user.experience
          @user.user_level = @user.user_level + 1
          @user.update(user_level: @user.user_level)
      end
      redirect_to posts_path
    else
      render 'index'
    end
  end

  def index
    @posts = Post.page(params[:page]).per(5).order("created_at DESC")
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def edit
  end

  def update
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:post, :post_image, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = @user.posts.page(params[:page]).per(5).order("created_at DESC")
    @posts = Post.all
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
			redirect_to user_path(current_user.id)
		end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success_notice] = '変更しました'
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def search
    @users = User.search(params[:search])
    render "index"
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile, :profile_image, :user_level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_sidebar.html.erb
<div class="col-3 sidebar">
  <div class="sidebar">
  <div class="navbar-brand">
    <%= link_to image_tag("logo.jpg"), root_path %>
  </div>
    <ul class="nav flex-column nav-pills nav-fill mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item btn btn-light">
          <%= link_to 'ホーム', posts_path, class:"nav-item nav-link" %>
        </li>
        <li class="nav-item btn btn-light">
          <%= link_to '投稿フォーム', new_post_path, class:"nav-item nav-link" %>
        </li>
        <li class="nav-item btn btn-light">
          <%= link_to 'プロフィール', user_path(current_user.id), class:"nav-item nav-link" %>
        </li>
        <li class="nav-item btn btn-light">
          <%= link_to "ログアウト", destroy_user_session_path, class:"nav-item nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item btn btn-light">
          <%= link_to "新規登録", new_user_registration_path, class:"nav-item nav-link" %>
        </li>
        <li class="nav-item btn btn-light">
          <%= link_to "ログイン", new_user_session_path, class:"nav-item nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/about.html.erb
<div class="top-image"></div>
  <%# image %>
  <div class="py-5 about-image1">
    <div style="height: 200px;"></div>
  </div>

  <%# Content %>
  <section class="py-5">
    <div class="container">
      <h1>お金</h1>
      <p class="lead">100年生きて、お金は足りるのか？</p>
      <small>寿命が伸び続け「人生100年時代」という言葉も出てきました。
            そんな時代では考えなしに老後を迎えると、先に尽きるのは寿命ではなく、お金になります。
            「 思っていたより長生きする」と考え、余裕をもってお金を準備しておきたいものです。</small><br/>
            今から準備しましょう。まずは目標宣言です。
    </div>
  </section>

  <%# image %>
  <div class="py-5 about-image2">
    <div style="height: 200px;"></div>
  </div>

  <%# Content %>
  <section class="py-5">
    <div class="container">
      <h1>友達</h1>
      <p class="lead">仕事や家庭を理由に、疎遠になっていたりしませんか？</p>
      <small>なにげなく会って話をしたり、気軽に遊びに出かけたり。10代の頃は当たり前にそこにありました。時が過ぎ、色んな環境の変化とともに友人との関係が途切れてしまうこともあるでしょう。</small><br/>
      今から予定を立てましょう。お出かけしたら思い出を書き残すのに使ってください。
    </div>
  </section>

  <%# image %>
  <div class="py-5 about-image3">
    <div style="height: 200px;"></div>
  </div>

  <%# Content %>
  <section class="py-5">
    <div class="container">
      <h1>筋肉</h1>
      <p class="lead">健康に気を遣う。今のカラダは、当たり前にあるものではない。</p>
      <small>筋肉が無ければ、何をするにも一苦労。お金があっても使い道が限られる。
              大切な友達とも遊びに行きにくい。<br/>
              老後の弱ったカラダになってから鍛えようと思っても大変ですよね？</small><br/>
              今から鍛えましょう。日々の成果を発信しましょう。
    </div>
  </section>


  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

app/views/home/top.html.erb
  <section class="content-section" id="about">
    <div class="container text-center">
      <div class="row">
        <div class="top-content col-lg-10 mx-auto">
          <h4 class="font-weight-bold mt-5 mb-5">「お金、友達、筋肉。」<br/>楽しい100年を過ごすために</h4>
          <p>夢や目標を発信しよう</p>

          <%= link_to  about_path, class:"btn btn-outline-success btn-lg" do %>
            <i class="fas fa-angle-double-right color:white;"> 詳しく</i>
          <% end %>
        </div>
      </div>
    </div>
  </section>