config/routes.rb
Rails.application.routes.draw do

  #googleAPI
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'home#top'
  get 'about', to: 'home#about'
  get "search", to: "users#search"

  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 500}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/level_setting.rb
class LevelSetting < ApplicationRecord
  validates :level, uniqueness: true
  validates :threshold, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_relations

  attachment :post_image

  validates :post, presence: true, length: { maximum: 500}

  # 引数で渡されたユーザidがFavoritesテーブル内user_idカラムに存在（exists?）するかどうかを調べる
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image, destroy: false

  # バリデーション
  validates :name, presence: true, length: { maximum: 20 }
  validates :profile, length: { maximum: 100 }
  validates :email, presence: true
# ゲストログイン
  def self.guest
    User.find_by(email: 'guest1@guest1')
  end
# google API
  protected
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    unless user
      user = User.create!(
        name: auth.info.name,
        email: auth.info.email,
        provider: auth.provider,
        uid: auth.uid,
        token: auth.credentials.token,
        password: Devise.friendly_token[0, 20],
        meta: auth.to_yaml)
    end
    user
  end
#検索機能
  def self.search(search)
    User.where(['name LIKE ?', "%#{search}%"])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @user = current_user
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = post.id
    @comment.save
      if @comment.save
        @user.experience +=1
        @user.save
        levelSetting = LevelSetting.find_by(level: @user.user_level + 1)
        if levelSetting.threshold <= @user.experience
          @user.user_level = @user.user_level + 1
          @user.update(user_level: @user.user_level)
        end
        redirect_to post_path(post)
      else
        redirect_to post_path(post)
      end
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end
  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # def new
  #   @post = Post.new(post_params)
  #   @post.user_id = current_user.id
  #   if @post.save
  #     @posts = Post.all
  #     @user.experience +=1
  #     @user.save
  #     levelSetting = LevelSetting.find_by(level: @user.user_level + 1)
  #     if levelSetting.threshold <= @user.experience
  #         @user.user_level = @user.user_level + 1
  #         @user.update(user_level: @user.user_level)
  #     end
  #   else
  #     render 'index'
  #   end
  # end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @user = current_user
    @posts = Post.page(params[:page]).per(5).order("created_at DESC")
    if @post.save
      @user.experience +=1
      @user.save
      levelSetting = LevelSetting.find_by(level: @user.user_level + 1)
      if levelSetting.threshold <= @user.experience
          @user.user_level = @user.user_level + 1
          @user.update(user_level: @user.user_level)
      end
      redirect_to posts_path
    else
      render 'index'
    end
  end

  def index
    @posts = Post.page(params[:page]).per(5).order("created_at DESC")
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def edit
  end

  def update
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:post, :post_image, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = @user.posts.page(params[:page]).per(5).order("created_at DESC")
    @posts = Post.all
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
			redirect_to user_path(current_user.id)
		end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success_notice] = '変更しました'
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def search
    @users = User.search(params[:search])
    render "index"
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile, :profile_image, :user_level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Life</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>
  <body>
    <div class="container">
    <div class="bg-image"></div>
    <div class="notice"></div>
      <div class="row justify-content-md-center">
        <%# サイドバー %>
        <div class="col-3 sidebar">
          <div class="sidebar">
            <div class="logo">
              <%= link_to image_tag("logo.jpg", width: "255", class:"logo" ), root_path %>
            </div>
            <div class="btn-group-vertical">
              <% if user_signed_in? %>
                <%= link_to posts_path, class:"btn btn-success nav-item", data: {"turbolinks"=>false} do %>
                  <i class="fas fa-home nav-font"> ホーム</i>
                <% end %>
                <%= link_to user_path(current_user.id), class:"btn btn-success nav-item", data: {"turbolinks"=>false} do %>
                  <i class="fas fa-user nav-font"> プロフィール</i>
                <% end %>
                <%= link_to users_path, class:"btn btn-success nav-item", data: {"turbolinks"=>false} do %>
                  <i class="fas fa-users nav-font"> メンバーズ</i>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class:"btn btn-success nav-item" do %>
                  <i class="fas fa-sign-out-alt nav-font"> ログアウト</i>
                <% end %>
              <% else %>
                <%= link_to new_user_registration_path, class:"btn btn-success nav-item" do %>
                  <i class="fas fa-pen nav-font"> 新規登録</i>
                <% end %>
                <%= link_to new_user_session_path, class:"btn btn-success nav-item" do %>
                  <i class="fas fa-sign-in-alt nav-font"> ログイン</i>
                <% end %>
                <%= link_to users_guest_sign_in_path, class:"btn btn-success nav-item", method: :post do %>
                  <i class="fas fa-sign-in-alt nav-font"> ゲストログイン（閲覧用）</i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <%# --------- %>
        <%# レスポンシブ %>
        <div class="navbar fixed-top justify-content-around">
          <h2>Life</h2>
        </div>
        <div class="navbar  fixed-bottom bg-light  justify-content-around ">
              <% if user_signed_in? %>
                <div class="navbar fixed-top justify-content-around">
                  <%= link_to posts_path, data: {"turbolinks"=>false} do %>
                    <h2>Life</h2>
                  <% end %>
                </div>
              <%# ホーム %>
                <%= link_to posts_path, class:"btn btn-success nav-item", data: {"turbolinks"=>false} do %>
                  <i class="fas fa-home nav-font"> </i>
                <% end %>
                <%# プロフィール %>
                <%= link_to user_path(current_user.id), class:"btn btn-success nav-item", data: {"turbolinks"=>false} do %>
                  <i class="fas fa-user nav-font"> </i>
                <% end %>
                <%# メンバーズ %>
                <%= link_to users_path, class:"btn btn-success nav-item", data: {"turbolinks"=>false} do %>
                  <i class="fas fa-users nav-font"> </i>
                <% end %>
                <%# ログアウト %>
                <%= link_to destroy_user_session_path, method: :delete, class:"btn btn-success nav-item" do %>
                  <i class="fas fa-sign-out-alt nav-font"> </i>
                <% end %>
              <% else %>
                <div class="navbar fixed-top justify-content-around">
                  <%= link_to root_path do%>
                    <h2>Life</h2>
                  <% end %>
                </div>
                <%= link_to new_user_registration_path, class:"btn btn-success nav-item" do %>
                  <i class="fas fa-pen nav-font"> 新規登録</i>
                <% end %>
                <%= link_to new_user_session_path, class:"btn btn-success nav-item" do %>
                  <i class="fas fa-sign-in-alt nav-font"> ログイン</i>
                <% end %>
                <%= link_to users_guest_sign_in_path, class:"btn btn-success nav-item", method: :post do %>
                  <i class="fas fa-sign-in-alt nav-font"> ゲストログイン（閲覧用）</i>
                <% end %>
              <% end %>
        </div>
        <div class="col-md-9 main-content-color">
          <% if flash[:notice] %>
            <p class="alert alert-success"><%= flash[:notice] %></p>
          <% end %>
          <% if flash[:alert] %>
            <p class="alert alert-warning"><%= flash[:alert] %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>